### PR TITLE
Server: Operational Webhook Eventtype Migration

### LINKED ISSUE #887: Operational Endpoints cannot be filtered by Operational Webhook event types
### Version

0.82.1

### Platform

Linux 74d00365c75d 5.10.102.1-microsoft-standard-WSL2 x86_64 GNU/Linux

### Description

Unable to specify which operational webhook events to subscribe/filter to. The API rejects a request to add an event filter to an operational webhook endpoint with an `HTTP 422`  when you try to add a event, (e.g. `message.attempt.failing` ) stating that:
"The following event types don't exist: `message.attempt.failing`"

The API request body I sent to `POST https://my.svix.address.goes.here/api/v1/app/{app_id}/endpoint/` used is here:

```
{
    "url": "https://any.old.url/srsly",
    "version": 1,
    "filterTypes": [
        "message.attempt.failing",
        "message.attempt.exhausted"
    ]
}

```

You should be able to specify the names of operational webhooks as `filterTypes` when creating OR updating an operational endpoint.

### PR DESCRIPTION
**Pull request by jaymell**
Adds migration to ensure that all operational webhook
types are populated in the database.

Fixes #887.

### CODE REVIEW

File: server/svix-server/src/core/security.rs [hunk 1]
```diff
@@ -26,7 +26,7 @@ pub fn default_org_id() -> OrganizationId {
     OrganizationId("org_23rb8YdGqMT0qIzpgGwdXfHirMu".to_owned())
 }
 
-/// The default org_id we use (useful for generating JWTs when testing).
+/// The default org_id -- used for sending Operational Webhooks
```
Comment (tasn) [inline server/svix-server/src/core/security.rs:29]:
```suggestion
/// The default Operational Webhooks org_id
```

**Review by tasn — DISMISSED** [review]

**Review by tasn — APPROVED** [review]
