### PR TITLE
Replace `unwrap()` with `expect()`

### LINKED ISSUE #280: Replace `unwrap` by `expect`, later by proper error handling
## Bug Report

I am filing this as a bug report because this is very likely to show up sooner or later and will cause confusion ("where did this panic occur and why?!")

`expect` with a message is preferred over `unwrap` (if panics are intended and the state is unrecoverable) or replaced by proper error handling. Looking at all code here and below: https://github.com/svix/svix-webhooks/blob/3bee36df5a6977b64c66275b475159857bca5e5c/server/svix-server/src/main.rs#L57

### Version

At least `0.51`.

### PR DESCRIPTION
**Pull request by svix-dylan**
Fixes #280.

Replaces `.unwrap()` with `.expect(error_message)`, which prints the str error_message if the preceding operation panics.

This draft PR currently represents an audit of _non-test_ unwraps where a panic is plausible. A few instances of reasonably confident unwraps, eg "`parse(CONSTANT).unwrap()`", are not included.

**What still needs to be done:**
- Reject some of these replacements? Perhaps not all `expect`s are necessary.
- Do we want to use specific language or include certain information (eg function names) in our `expect` messages?

### CODE REVIEW

File: server/svix-server/src/core/types.rs [hunk 1]
```diff
@@ -87,15 +87,15 @@ macro_rules! json_wrapper {
...
+                let v = serde_json::to_value(v).expect("Error serializing JSON");
                 Self::Json(Some(Box::new(v)))
             }
         }
 
         impl TryGetable for $name_id {
             fn try_get(res: &QueryResult, pre: &str, col: &str) -> Result<Self, TryGetError> {
                 match Json::try_get(res, pre, col) {
-                    Ok(v) => Ok(serde_json::from_value(v).unwrap()),
+                    Ok(v) => Ok(serde_json::from_value(v).expect("Error serializing JSON")),
```
Comment (tasn) [inline server/svix-server/src/core/types.rs:98]: The error message both here and in the one above says "serializing" though one is `to_` and one is `from_`.

File: server/svix-server/src/lib.rs [hunk 2]
```diff
@@ -65,15 +71,15 @@ pub async fn run(cfg: Configuration, listener: Option<TcpListener>) {
     let with_api = cfg.api_enabled;
     let with_worker = cfg.worker_enabled;
 
-    let listen_address = SocketAddr::from_str(&cfg.listen_address).unwrap();
-
+    let listen_address =
+        SocketAddr::from_str(&cfg.listen_address).expect("Error coercing http address");
```
Comment (tasn) [inline server/svix-server/src/lib.rs:75]: I wouldn't call it coercing nor http address. Maybe "failed parsing server listen address".

File: server/svix-server/src/lib.rs [hunk 3]
```diff
@@ -65,15 +71,15 @@ pub async fn run(cfg: Configuration, listener: Option<TcpListener>) {
...
     let (server, worker_loop) = tokio::join!(
         async {
             if with_api {
                 if let Some(l) = listener {
                     tracing::debug!("API: Listening on {}", l.local_addr().unwrap());
                     axum::Server::from_tcp(l)
-                        .unwrap()
+                        .expect("Error starting http server")
```
Comment (tasn) [inline server/svix-server/src/lib.rs:82]: Just to confirm, does unwrap() hide the actual underlying error, or just supplement it?

File: server/svix-server/src/core/types.rs [hunk 4]
```diff
@@ -166,7 +168,7 @@ pub trait BaseId: Deref<Target = String> {
 fn validate_limited_str(s: &str) -> std::result::Result<(), ValidationErrors> {
     const MAX_LENGTH: usize = 256;
     lazy_static! {
-        static ref RE: Regex = Regex::new(r"^[a-zA-Z0-9\-_.]+$").unwrap();
+        static ref RE: Regex = Regex::new(r"^[a-zA-Z0-9\-_.]+$").expect("Error compiling Regex");
```
Comment (tasn) [inline server/svix-server/src/core/types.rs:171]: The idea was to add clarity, this doesn't really add clarity, it just restates what the error message will have anyway.
I think it should stay unwrap everywhere, and become expect only where it adds clarity (mainly main.rs, lib.rs, cfg.rs, and maybe db/mod.rs. Potentially other places too, such as worker.rs).

File: server/svix-server/src/worker.rs [hunk 5]
```diff
@@ -298,10 +311,10 @@ pub async fn worker_loop(
                         tokio::spawn(async move {
                             if let Err(err) = dispatch(cfg, &pool, cache, &queue_tx, msg).await {
                                 tracing::error!("Error executing task: {}", err);
-                                queue_tx.nack(delivery).await.unwrap();
+                                queue_tx.nack(delivery).await.expect("Error executing task");
```
Comment (tasn) [inline server/svix-server/src/worker.rs:314]: This is not what this error means, it's an error contact redis when trying to nack (needs better wording).

File: server/svix-server/src/lib.rs (hunk 3 above)
Comment (tasn) [reply server/svix-server/src/lib.rs:82]: Cool, perfect!

File: server/svix-server/src/core/types.rs (hunk 4 above)
Comment (tasn) [reply server/svix-server/src/core/types.rs:171]: Actually, given your other comment showing the shitty error messages in unwrap, I wonder whether it makes sense to keep these changes. I just hate the development burden for the little added benefit. What do you think?

File: server/svix-server/src/worker.rs [hunk 6]
```diff
@@ -131,7 +135,13 @@ async fn dispatch(
...
             &endp.url,
         );
-        headers.insert("user-agent", USER_AGENT.to_string().parse().unwrap());
+        headers.insert(
+            "user-agent",
+            USER_AGENT
+                .to_string()
+                .parse()
+                .expect("Error parsing user-agent"),
+        );
```
[the remark this answers is not in the document]
Comment (tasn) [reply server/svix-server/src/worker.rs:144]: Perfect, yeah.

File: server/svix-server/src/core/types.rs [hunk 7]
```diff
@@ -110,7 +110,9 @@ macro_rules! json_wrapper {
         impl ValueType for $name_id {
             fn try_from(v: Value) -> Result<Self, ValueTypeErr> {
                 match v {
-                    Value::Json(Some(x)) => Ok(serde_json::from_value(*x).unwrap()),
+                    Value::Json(Some(x)) => {
+                        Ok(serde_json::from_value(*x).expect("Error serializing JSON"))
```
Comment (svix-dylan) [inline server/svix-server/src/core/types.rs:114]:
```suggestion
                        Ok(serde_json::from_value(*x).expect("Error deserializing JSON"))
```

**Comment by svix-dylan** [comment]
Recapping changes discussed above:

- Removed some replacements from "internal" logic. We will leave these as `unwrap()`s for now, and handle potential errors properly in a separate issue.
- Clarified some of the `expect()` error messages.

**Review by svix-james — APPROVED** [review]
